---
# tasks file for caddy2

- name: installing pre-requisits (debian)
  apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

#- name: obtaining caddy2 apt key
#  ansible.builtin.get_url:
#    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
#    dest: /etc/apt/trusted.gpg.d/caddy-stable.asc
#    mode: '0644'

- name: adding caddy gpg key
  become: yes
  shell: curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --always-trust -r --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  when: ansible_facts['os_family'] == "Debian"

- name: configuring caddy2 repository
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt
    dest: /etc/apt/sources.list.d/caddy-stable.list
    mode: '0644'

- name: installing caddy2 (debian)
  apt:
    name: caddy
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: stopping caddy service
  systemd:
    name: caddy
    state: stopped
