---
# tasks file for caddy2

- name: installing pre-requisits (debian)
  apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"