---
# tasks file for caddy2

- name: installing pre-requisits
  become: yes
  apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
    state: present
    update_cache: yes

- name: adding caddy apt key
  become: yes
  shell: |
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor --yes -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg

#- name: adding caddy apt key
#  become: yes
#  apt_key:
#      url: "https://dl.cloudsmith.io/public/caddy/stable/gpg.key"
#      state: present

- name: configuring caddy2 repository
  become: yes
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt
    dest: /etc/apt/sources.list.d/caddy-stable.list
    mode: '0644'

#- name: configuring caddy2 repository
#  become: yes
#  apt_repository:
#      repo: "deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
#      state: present
#      update_cache: true

- name: installing caddy2
  become: yes
  apt:
    name: caddy
    state: present
    update_cache: yes

- name: stopping caddy service
  become: yes
  systemd:
    name: caddy
    state: stopped

- name: copying Caddyfile
  become: yes
  template:
    src: Caddyfile.j2
    dest: "/etc/caddy/Caddyfile"
    mode: "u=rwX,g=rX,o=rX"
    owner: "{{ caddy2_file_owner | default('root') }}"
    group: "{{ caddy2_file_group | default('root') }}"

- name: ensure /usr/local/share/ca-certificates exists
  become: yes
  file:
    path: /usr/local/share/ca-certificates
    state: directory
    mode: '0644'

- name: send internal ca's to be trusted
  become: yes
  copy:
    src: "{{ ca_trusted }}"
    dest: /usr/local/share/ca-certificates/
  loop: "{{ internal_ca_certs }}"
  loop_control: 
    loop_var: ca_trusted
  when: 
    - internal_ca_certs is defined

- name: trust internal ca's
  become: yes
  shell: |
    update-ca-certificates
  when: 
    - internal_ca_certs is defined

- name: starting and enabling caddy service
  become: yes
  systemd:
    name: caddy
    state: started
    enabled: yes