---
# tasks file for caddy2
- name: loading native tasks
  include_tasks: install_native.yml
  when: caddy2_install_type == "native"

- name: loading docker install tasks
  include_tasks: install_docker.yml
  when: caddy2_install_type == "docker"
