---
# tasks file for caddy2
- name: loading native tasks
  include_tasks: install.yml
  when: caddy2_state == 'present'

- name: loading docker install tasks
  include_tasks: remove.yml
  when: caddy2_state != 'present'
